name: Engranajes
markdown: redcarpet
owner:
  email: info@usaesto.es
pygments: true
permalink: /:title/

# Misc
timezone: Europe/Madrid

links:
  -
    external: false
    url: /acerca-de
    title: Acerca de

# Excluding stuff from the _site folder
exclude: ['Rakefile', 'README.markdown']

