name: Engranajes
description: Entrevistas a personajes sobre sus herramientas de trabajo.
url:
markdown: redcarpet
owner:
  name: Engranajes
  email: info@usaesto.es
  twitter: los_engranajes
pygments: true
permalink: /:title/

# Misc
timezone: Europe/Madrid

links:
  -
    external: false
    url: /acerca-de
    title: Acerca de

# Excluding stuff from the _site folder
exclude: []

