name: Engranajes
title: Engranajes
markdown: redcarpet
owner:
  name: Engranajes
  email: info@usaesto.es
  twitter: los_engranajes
pygments: true
permalink: /:title/

# Misc
timezone: Europe/Madrid

links:
  -
    external: false
    url: /acerca-de
    title: Acerca de

# Excluding stuff from the _site folder
exclude: ['Rakefile', 'README.markdown']
